/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as TrilhasRouteImport } from './routes/trilhas'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as CursosRouteImport } from './routes/cursos'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidarCertificadoCodigoRouteImport } from './routes/validar-certificado.$codigo'
import { Route as CursosSlugRouteImport } from './routes/cursos.$slug'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCertificadosRouteImport } from './routes/_authenticated/certificados'
import { Route as AuthenticatedQuizModuleIdRouteImport } from './routes/_authenticated/quiz.$moduleId'
import { Route as AuthenticatedCursoSlugRouteImport } from './routes/_authenticated/curso.$slug'
import { Route as AuthenticatedCertificadosIdRouteImport } from './routes/_authenticated/certificados.$id'

const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasRoute = TrilhasRouteImport.update({
  id: '/trilhas',
  path: '/trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const CursosRoute = CursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarCertificadoCodigoRoute =
  ValidarCertificadoCodigoRouteImport.update({
    id: '/validar-certificado/$codigo',
    path: '/validar-certificado/$codigo',
    getParentRoute: () => rootRouteImport,
  } as any)
const CursosSlugRoute = CursosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CursosRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosRoute =
  AuthenticatedCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizModuleIdRoute =
  AuthenticatedQuizModuleIdRouteImport.update({
    id: '/quiz/$moduleId',
    path: '/quiz/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCursoSlugRoute = AuthenticatedCursoSlugRouteImport.update({
  id: '/curso/$slug',
  path: '/curso/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificadosIdRoute =
  AuthenticatedCertificadosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCertificadosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/trilhas': typeof TrilhasRoute
  '/turmas': typeof TurmasRoute
  '/certificados': typeof AuthenticatedCertificadosRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/validar-certificado/$codigo': typeof ValidarCertificadoCodigoRoute
  '/certificados/$id': typeof AuthenticatedCertificadosIdRoute
  '/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/trilhas': typeof TrilhasRoute
  '/turmas': typeof TurmasRoute
  '/certificados': typeof AuthenticatedCertificadosRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/validar-certificado/$codigo': typeof ValidarCertificadoCodigoRoute
  '/certificados/$id': typeof AuthenticatedCertificadosIdRoute
  '/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cursos': typeof CursosRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/trilhas': typeof TrilhasRoute
  '/turmas': typeof TurmasRoute
  '/_authenticated/certificados': typeof AuthenticatedCertificadosRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/cursos/$slug': typeof CursosSlugRoute
  '/validar-certificado/$codigo': typeof ValidarCertificadoCodigoRoute
  '/_authenticated/certificados/$id': typeof AuthenticatedCertificadosIdRoute
  '/_authenticated/curso/$slug': typeof AuthenticatedCursoSlugRoute
  '/_authenticated/quiz/$moduleId': typeof AuthenticatedQuizModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cursos'
    | '/empresas'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/trilhas'
    | '/turmas'
    | '/certificados'
    | '/dashboard'
    | '/profile'
    | '/cursos/$slug'
    | '/validar-certificado/$codigo'
    | '/certificados/$id'
    | '/curso/$slug'
    | '/quiz/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cursos'
    | '/empresas'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/trilhas'
    | '/turmas'
    | '/certificados'
    | '/dashboard'
    | '/profile'
    | '/cursos/$slug'
    | '/validar-certificado/$codigo'
    | '/certificados/$id'
    | '/curso/$slug'
    | '/quiz/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cursos'
    | '/empresas'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/trilhas'
    | '/turmas'
    | '/_authenticated/certificados'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/cursos/$slug'
    | '/validar-certificado/$codigo'
    | '/_authenticated/certificados/$id'
    | '/_authenticated/curso/$slug'
    | '/_authenticated/quiz/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CursosRoute: typeof CursosRouteWithChildren
  EmpresasRoute: typeof EmpresasRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InscricaoRoute: typeof InscricaoRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TrilhasRoute: typeof TrilhasRoute
  TurmasRoute: typeof TurmasRoute
  ValidarCertificadoCodigoRoute: typeof ValidarCertificadoCodigoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas': {
      id: '/trilhas'
      path: '/trilhas'
      fullPath: '/trilhas'
      preLoaderRoute: typeof TrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar-certificado/$codigo': {
      id: '/validar-certificado/$codigo'
      path: '/validar-certificado/$codigo'
      fullPath: '/validar-certificado/$codigo'
      preLoaderRoute: typeof ValidarCertificadoCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cursos/$slug': {
      id: '/cursos/$slug'
      path: '/$slug'
      fullPath: '/cursos/$slug'
      preLoaderRoute: typeof CursosSlugRouteImport
      parentRoute: typeof CursosRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados': {
      id: '/_authenticated/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof AuthenticatedCertificadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quiz/$moduleId': {
      id: '/_authenticated/quiz/$moduleId'
      path: '/quiz/$moduleId'
      fullPath: '/quiz/$moduleId'
      preLoaderRoute: typeof AuthenticatedQuizModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/curso/$slug': {
      id: '/_authenticated/curso/$slug'
      path: '/curso/$slug'
      fullPath: '/curso/$slug'
      preLoaderRoute: typeof AuthenticatedCursoSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificados/$id': {
      id: '/_authenticated/certificados/$id'
      path: '/$id'
      fullPath: '/certificados/$id'
      preLoaderRoute: typeof AuthenticatedCertificadosIdRouteImport
      parentRoute: typeof AuthenticatedCertificadosRoute
    }
  }
}

interface AuthenticatedCertificadosRouteChildren {
  AuthenticatedCertificadosIdRoute: typeof AuthenticatedCertificadosIdRoute
}

const AuthenticatedCertificadosRouteChildren: AuthenticatedCertificadosRouteChildren =
  {
    AuthenticatedCertificadosIdRoute: AuthenticatedCertificadosIdRoute,
  }

const AuthenticatedCertificadosRouteWithChildren =
  AuthenticatedCertificadosRoute._addFileChildren(
    AuthenticatedCertificadosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCertificadosRoute: typeof AuthenticatedCertificadosRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCursoSlugRoute: typeof AuthenticatedCursoSlugRoute
  AuthenticatedQuizModuleIdRoute: typeof AuthenticatedQuizModuleIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCertificadosRoute: AuthenticatedCertificadosRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCursoSlugRoute: AuthenticatedCursoSlugRoute,
  AuthenticatedQuizModuleIdRoute: AuthenticatedQuizModuleIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CursosRouteChildren {
  CursosSlugRoute: typeof CursosSlugRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosSlugRoute: CursosSlugRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CursosRoute: CursosRouteWithChildren,
  EmpresasRoute: EmpresasRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InscricaoRoute: InscricaoRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TrilhasRoute: TrilhasRoute,
  TurmasRoute: TurmasRoute,
  ValidarCertificadoCodigoRoute: ValidarCertificadoCodigoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
